- name: Setup NGINX
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Update
      apt:
        update_cache: true
        upgrade: dist
        force_apt_get: true
    - name: Install NGINX
      apt:
        pkg:
          - nginx
        update_cache: yes
        state: latest
